name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 5.0.x
    - name: Build Test Cases
      run: dotnet build -c Debug TestCases/
    - name: Build Test CLI
      run: dotnet build -c Debug ILRuntimeTestCLI/
    - name: Test
      run: dotnet run --no-build --verbosity normal ILRuntimeTestCLI/
