name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          2.0.x
    - name: Build Test Cases
      run: |
        dotnet build TestCases/
        dotnet build -c Release TestCases/
    - name: Test Debug
      run: |
        dotnet run --verbosity normal --project ILRuntimeTestCLI/ILRuntimeTestCLI.csproj TestCases/bin/Debug/netstandard2.0/TestCases.dll false
        dotnet run --no-build --verbosity normal --project ILRuntimeTestCLI/ILRuntimeTestCLI.csproj TestCases/bin/Debug/netstandard2.0/TestCases.dll true
        dotnet run --no-build --verbosity normal --project ILRuntimeTestCLI/ILRuntimeTestCLI.csproj TestCases/bin/Release/netstandard2.0/TestCases.dll false
        dotnet run --no-build --verbosity normal --project ILRuntimeTestCLI/ILRuntimeTestCLI.csproj TestCases/bin/Release/netstandard2.0/TestCases.dll true
    - name: Test Release
      run: |
        dotnet run -c Release --verbosity normal --project ILRuntimeTestCLI/ILRuntimeTestCLI.csproj TestCases/bin/Debug/netstandard2.0/TestCases.dll false
        dotnet run -c Release --no-build --verbosity normal --project ILRuntimeTestCLI/ILRuntimeTestCLI.csproj TestCases/bin/Debug/netstandard2.0/TestCases.dll true
        dotnet run -c Release --no-build --verbosity normal --project ILRuntimeTestCLI/ILRuntimeTestCLI.csproj TestCases/bin/Release/netstandard2.0/TestCases.dll false
        dotnet run -c Release --no-build --verbosity normal --project ILRuntimeTestCLI/ILRuntimeTestCLI.csproj TestCases/bin/Release/netstandard2.0/TestCases.dll true
