name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build Test Cases Debug
      run: dotnet build --no-restore TestCases/
    - name: Build Test Cases Release
      run: dotnet build --no-restore TestCases/
    - name: Test Debug
      run: dotnet run --no-build --verbosity normal ILRuntimeTestCLI/
